# Generated by Django 4.2.7 on 2023-12-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "building",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("room_number", models.CharField(max_length=7, unique=True)),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "db_table": "classroom",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "credits",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("building", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="ID", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "db_table": "instructor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prereq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "prereq",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="ID", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "tot_cred",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Takes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "db_table": "takes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teaches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "teaches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "time_slot_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("day", models.CharField(max_length=1)),
                ("start_hr", models.DecimalField(decimal_places=0, max_digits=2)),
                ("start_min", models.DecimalField(decimal_places=0, max_digits=2)),
                (
                    "end_hr",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
                (
                    "end_min",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
            ],
            options={
                "db_table": "time_slot",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Advisor",
            fields=[
                (
                    "s",
                    models.OneToOneField(
                        db_column="s_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="controlescolar.student",
                    ),
                ),
            ],
            options={
                "db_table": "advisor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="controlescolar.course",
                    ),
                ),
                ("sec_id", models.CharField(max_length=8, unique=True)),
                ("semester", models.CharField(max_length=6, unique=True)),
                (
                    "year",
                    models.DecimalField(decimal_places=0, max_digits=4, unique=True),
                ),
                ("time_slot_id", models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                "db_table": "section",
                "managed": False,
            },
        ),
    ]
